INSERT INTO COUNTRY (ID, COUNTRY_NAME  ,CITY_NAME) VALUES (1, 'USA','New York');
INSERT INTO COUNTRY (ID, COUNTRY_NAME  ,CITY_NAME) VALUES (2, 'Germany','Berlin');
INSERT INTO COUNTRY (ID, COUNTRY_NAME  ,CITY_NAME) VALUES (3, 'Brazil','quto ricko');
INSERT INTO COUNTRY (ID, COUNTRY_NAME  ,CITY_NAME) VALUES (4, 'Italy','Milan');
INSERT INTO COUNTRY (ID, COUNTRY_NAME  ,CITY_NAME) VALUES (5, 'Canada','Manchester');